language: python
os:
  - linux
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  - "pypy"
  - "pypy3"
script:
  - python -c "import Go; exit(int(not Go.tests.run()))"
